{
  imports = [
    ./windowManager.nix
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./env.nix
    ./net.nix
    ./nix.nix
    ./timezone.nix
    ./sddm.nix
    ./tlp.nix
    ./fonts.nix
    ./security.nix
    ./pkgs.nix
    ./hardware.nix
    ./services/services.nix
    ./services/xorg.nix
    ./programs.nix
  ];
}
