{
  imports = [
    ./windowManager.nix
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./env.nix
    ./net.nix
    ./nix.nix
    ./timezone.nix
    ./sddm.nix
    ./fonts.nix
    ./security.nix
    ./hardware.nix
    ./services/xorg.nix
    ./services/services.nix
    ./services/systemd-timers.nix
    ./services/tlp.nix
    ./programs.nix
    ./systemPkgs.nix
  ];
}
